
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";
import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'JP-dev',
  description: 'Generated by JP-dev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="fr">
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <Toaster position="top-right" toastOptions={{duration: 3000}} />
        {children}
        <Footer />
        <Analytics />
        <SpeedInsights />
      </body>
      
    </html>
  )
}
