
import "./globals.css";
import { Inter } from "next/font/google";
import {NextUIProvider} from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: 'JP-dev',
  description: 'Generated by JP-dev',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // <NextUIProvider>
      <html lang="fr" >
        <body className={`${inter.className}`}>
          {children}
        </body>
      </html>
    // </NextUIProvider>
  )
}
